CREATE TABLE `bgo`.`admin` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(60) NOT NULL,
  `ctime` BIGINT NOT NULL,
  `mtime` BIGINT NOT NULL,
  `dtime` BIGINT NOT NULL DEFAULT 0,
  `ltime` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));