version: '3'
volumes:
  bgo:
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'bgo'
      MYSQL_ROOT_PASSWORD: '123456'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - '3306:3306'
    volumes:
      - bgo:/var/lib/mysql
